project:
  type: website
  output-dir: docs
  preview:
    port: 4269

title: "LLMs on Polaris"
date: today
date-modified: last-modified
favicon: "./favicon.svg"
author-title: ""
affiliation-title: ""
published-title: ""
modified-title: ""
title-block-categories: false
number-sections: false
bibliography: references.bib
appendix-cite-as: display
google-scholar: true
google-analytics: G-XVM2Y822Y1
# favicon: "./assets/favicon.svg"
# format:
#   html:
#     syntax-definitions:
#       - ./docs/python.xml
#
website:
  favicon: "./favicon.svg"
  description: "LLMs on Polaris (2023-10-11)"
  twitter-card:
    image: "https://github.com/saforem2/llm-lunch-talk/blob/main/docs/assets/thumbnail.png?raw=true"
    site: "@saforem2"
    creator: "@saforem2"

author:
  name: Sam Foreman
  url: https://samforeman.me
  orcid: 0000-0002-9981-0876
  email: foremans@anl.gov
  affiliation: Argonne National Laboratory
  affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
citation:
   author: Sam Foreman
   type: speech
   title: "LLMs at ALCF"
   url: https://saforem2.github.io/llm-lunch-talk
format:
  html:
    callout-appearance: simple
    code-link: true
    code-line-numbers: false
    toc: true
    self-contained: false
    toc-location: right
    grid:
      body-width: 1150px
    fig-responsive: true
    anchor-sections: true
    # highlight-style: atom-one
    code-overflow: scroll
    code-fold: false
    code-copy: false
    code-summary: " "
    code-tools:
      source: repo
      toggle: true
      caption: none
    html-math-method: katex
    css:
      - css/default.css
      - css/callouts.css
      # - css/profile.css
    theme:
      light:
        - css/common.scss
        - css/light.scss
        - css/syntax-light.scss
        - css/callout-cards.scss
      dark:
        - css/common.scss
        - css/dark.scss
        - css/syntax-dark.scss
        - css/callout-cards.scss
    smooth-scroll: false
    citations-hover: true
    footnotes-hover: true
    header-includes: |
      <link href="https://pvinis.github.io/iosevka-webfont/3.4.1/iosevka.css" rel="stylesheet" />
  revealjs:
    code-line-numbers: false
    code-link: false
    code-copy: false
    # callout-appearance: simple
    # syntax-definitions:
    #   - ./docs/python.xml
    scrollable: true
    title-block-style: none
    slide-number: c
    title-slide-style: default
    chalkboard:
      buttons: false
    auto-animate: true
    reference-location: section
    touch: true
    pause: false
    footnotes-hover: true
    citations-hover: true
    preview-links: true
    controls-tutorial: true
    controls: false
    logo: "assets/anl.svg"
    history: false
    highlight-style: "atom-one"
    # theme: [dark, css/dark.scss]
    # css: [css/default.css, css/callouts-html.css]
    css:
      - css/default.css
      - css/callouts-html.css
    # theme: [css/light.scss, css/common.scss, css/syntax-light.scss]
    theme:
      - white
      # - css/light.scss
      - css/common.scss
      - css/syntax-light.scss
      - css/pdf.scss
      # dark:
      #   - css/dark.scss
      #   - css/common.scss
      #   - css/syntax-dark.scss
    # css: [css/default.css, css/callouts.css, css/code-callout.css]
    self-contained: false
    embed-resources: false
    self-contained-math: false
    center: true
    default-image-extension: svg
    code-overflow: scroll
    html-math-method: katex
    fig-align: center
    mermaid:
      theme: dark
  gfm:
    author: Sam Foreman
    output-file: "README.md"
# include-in-header:
#   text: |
#     <script src="https://unpkg.com/shiki"></script>
#     <script>
#       shiki
#         .getHighlighter({
#           theme: 'dracula',
#           langs: ['python', 'html', 'bash', 'markdown', 'js', 'css'],
#         })
#         .then(highlighter => {
#           const code = highlighter.codeToHtml(`console.log('shiki');`, { lang: 'js' })
#             document.getElementById('output').innerHTML = code
#         })
#     </script>
   # genre: "Presentation at the 2023 International Symposium on Lattice Field Theory"
   # container-title: https://indico.fnal.gov/event/57249/contributions/271305/
   # title: "MLMC: Machine Learning Monte Carlo for Lattice Gauge Theory"
   # url: https://saforem2.github.io/lattice23
   # abstract: | 
   #   We present a trainable framework for efficiently generating gauge
   #   configurations, and discuss ongoing work in this direction. In particular, we
   #   consider the problem of sampling configurations from a 4D 𝑆𝑈(3) lattice gauge
   #   theory, and consider a generalized leapfrog integrator in the molecular
   #   dynamics update that can be trained to improve sampling efficiency.
  # -----------------------
  # type: article-journal
  # container-title: ACM Transactions on Embedded Computing Systems
  # volume: 21
  # issue: 2
  # issued: 2022-03
  # issn: 1539-9087
  # doi: 10.1145/3514174
  # -----------------------
  # type: speech
  # container-title: "Journal of Data Science Software"
  # doi: "10.23915/reprodocs.00010"
  # url: https://example.com/summarizing-output
  # -----------------------

#
#
#
#
#
# # website:
# #   page-navigation: true
# #   title: "MLMC: Machine Learning Monte Carlo"
# #   # site-url: "https://saforem2.github.io/mlmc"
# #   # favicon: "./assets/favicon.svg"
# appendix-cite-as: display	
# citation:
#    type: speech
#    genre: "Presentation at the 2023 International Symposium on Lattice Field Theory"
#    container-title: https://indico.fnal.gov/event/57249/contributions/271305/
#    title: "MLMC: Machine Learning Monte Carlo for Lattice Gauge Theory"
#    url: https://saforem2.github.io/lattice23
# author:
#   - name: Sam Foreman
#     # id: sf
#     url: https://samforeman.me
#     orcid: 0000-0002-9981-0876
#     email: foremans@anl.gov
#     affiliation: "Argonne National Laboratory"
#     affiliation-url: https://alcf.anl.gov/about/people/sam-foreman
#
#     # affiliation: 
#     #   - name: Argonne National Laboratory
#     #     city: Chicago
#     #     state: IL
#     #     url: https://alcf.anl.gov
#     #
# favicon: "./assets/favicon.svg"
# google-analytics: G-XVM2Y822Y1
# # title: A Published Conference Paper
# # author:
# #   - name: Norah Jones
# #     affiliation: School of Hard Knocks
# #     orcid: 0000-0001-8715-9476
# # citation:
# #   type: paper-conference
# #   container-title: "Proceedings of the annual conference of the Society for Research"
# #   publisher: "Society for Research"
# #   issued: 2020/09/23
# #   volume: 2
# #   doi: "10.23915/reprodocs.00010"
# #   url: https://example.com/summarizing-output
# #   page-first: 46
# #   page-last: 53
# #   editor:
# #   - Don Draper
# #   - Nick Fury
# # google-scholar: true  
# #
# #
# # affiliation: ""
# # date: ""
# # toc: true
# filters:
#   - lua/callouts.lua
# highlight-style:
#   dark: dracula
#   light: dracula-light

